travis:
  secure:
    BINSTAR_TOKEN: cQDyl99+WBNwqqgtBti5zar9dgJcFKHurY/7isEe6UarYlYZlOFcrhd3UHjXOcwmNnp08IQCzpswh7sUIJ0Tpmoer6luTeWBvzOAfKm4TqwX3Qzp+JQR2/og6rOZFyhrturOd5gH95qX6g5rDmXYM9rbDIEreQeeXQJjo2V/Z3NdIuGHW20sYk8vrGhOV9fsBvaFm/mdCXRayw+NARYWmAC1BW7MrWaWilfQNuSlTxdjpw6kVPM9ANpKEPogmgL1ja6/WetGV8GaVr8+DaXeIG4ew5X6DfZ8gUXr1uaVKQl/vquHzHNMR2lJEd+JBko8Pq8MR6QffN7Ql6pqmW3m9rHR7kmel3ema4Ulbg3Gaqxe1vmvWb2FSfq260DvxyYwsfcQcKP2KibO5JXemup+/JIB5H9ZT7OkQ79P5lyTKBusSLTfoRH3b+KQpPwSMwgq8JQ6g9NoMpyaDzcCHdC419NoWvhYcXvHkuLtRiLxyBMya8ngOUILU+8o/VK2y3bDM3MFzmRR5LGkLLOILYCa4PbExzJ1KZ175OLuAZg7KunIN4S6gj1S8m2I/i9pUa0v0RJ/HXC1sbJD1BuY10HJO2saF3ss/0KVxR7Ak0hOXx+fuGW/7cLjchbNfX758K3MZY+ShSq3m7duYFghV50m1S8op8qiuMiopyv2UUjgPu0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
