travis:
  secure:
    BINSTAR_TOKEN: dfZdFuWRQIilFtdeJoLupAYt4mWO3ViV2UUqHwVXM0ZKrJXVly8xNyvA7SPhSzRBLD4sS0x13c/Zs5O5JaYcs+BO1VEWwWNzKHQrN+48wMxi1cf29eTHxNc+d+ESXokeToGGiTKrYh16KcjPhZQuIA1n+dYZhloVQK6IJTzPF4dbja0e4uIrMLQ0cj0jgpqjtdc4Mw59exsSix+/U+Ikm9qgNlI52yROqXvE5v1LGxFptHuxympv9u4oKqQqJHIg1eZNTqK7BwMuBSE7Xp/xr0YEPJoZkZce+kOF3vLp/+P1gf+7MBmK+Azj5qd1CgACNbu4sqsDO3IxS4CYKoqdqBh4pQwRnujCA8zhqBu6Pj8Yd+X421kRiCe3Tr2m8+OLbRHAKEwGvlybDKXAf3Iv08bNsO599ejSCA4QctdWkJ2FUhSAYwgwumUWPjTIQoU1dMjgxo0MFeOATa3Uq++S2Z5FLalf3PKVurJdergnOWDCtRZvA45MyMih1EHg6c/MrLcKbx8JJEvASl2YXDk9d7BbFhsPBltJjcLx7L3VdAvtO1icQRnxEeqwIK0K0dJ1h5JPXHsf0GhsSEtlyeweiaKYKRh4gbtP3sAWC695UKPufpAcwvJ7ym9zoXFOBmudwK7uxvCJ4TNoiSMzN56/xzjo7LNtptTRQGwQpmVy8yg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
